import { SiliconGate } from '../types';

export const SILICON_GATES: SiliconGate[] = [
  {
    gateNumber: 0,
    milestone: 'DR0',
    name: 'M33 Ring Product Vector Unit',
    category: 'Hardware/DR0-10',
    algorithm: 'Polynomial Ring Arithmetic (Rq)',
    description: 'Direct SIMD vectorization of negacyclic polynomial ring multiplication over R_q with 512-bit vector registers.',
    testCount: 24,
    passedCount: 24,
    avgRuntimeMs: 920,
    textMemoryBytes: 8192,
    tileRamBytes: 32768,
    dmaChannels: 2,
    tilesUsed: 1,
    zeroHostFallback: true,
    objectFifos: ['fifo_poly_a', 'fifo_poly_b', 'fifo_accum_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 1,
    milestone: 'DR1',
    name: 'ML-DSA-44 ExpandA / RejNTT',
    category: 'FIPS 204',
    algorithm: 'Lattice Matrix ExpandA Stream',
    description: 'Hardware streaming rejection filter & NTT sampler for ML-DSA-44 matrix generation on physical AIE2 tiles.',
    testCount: 33,
    passedCount: 33,
    avgRuntimeMs: 760,
    textMemoryBytes: 9400,
    tileRamBytes: 36864,
    dmaChannels: 2,
    tilesUsed: 2,
    zeroHostFallback: true,
    objectFifos: ['fifo_rho_seed', 'fifo_matrix_ntt_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 2,
    milestone: 'DR2a',
    name: 'ML-KEM-512 SampleNTT Stream',
    category: 'FIPS 203',
    algorithm: 'Bounded Uniform Sampling (SampleNTT)',
    description: 'Bit-exact 12-bit coefficient unpacker with modulus rejection filter q=3329 running at wire speed.',
    testCount: 13,
    passedCount: 13,
    avgRuntimeMs: 690,
    textMemoryBytes: 7168,
    tileRamBytes: 28672,
    dmaChannels: 1,
    tilesUsed: 1,
    zeroHostFallback: true,
    objectFifos: ['fifo_shake128_stream', 'fifo_sample_ntt'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 3,
    milestone: 'DR2b',
    name: 'ML-KEM-512 CBD3/NTT Noise Engine',
    category: 'FIPS 203',
    algorithm: 'Centered Binomial Noise (CBD3)',
    description: 'Fused PRF expansion, centered binomial distribution sampling (eta=3), and forward Cooley-Tukey NTT pipeline.',
    testCount: 13,
    passedCount: 13,
    avgRuntimeMs: 680,
    textMemoryBytes: 10240,
    tileRamBytes: 40960,
    dmaChannels: 2,
    tilesUsed: 2,
    zeroHostFallback: true,
    objectFifos: ['fifo_sigma_nonce', 'fifo_cbd_noise_ntt'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 4,
    milestone: 'DR2c',
    name: 'ML-KEM-512 KeyGen Matrix Row Accumulator',
    category: 'FIPS 203',
    algorithm: 'Lattice Row Vector Product',
    description: 'Hardware point-to-point accumulation pipeline for ML-KEM-512 public key vector generation (t = A*s + e).',
    testCount: 11,
    passedCount: 11,
    avgRuntimeMs: 720,
    textMemoryBytes: 11264,
    tileRamBytes: 45056,
    dmaChannels: 2,
    tilesUsed: 2,
    zeroHostFallback: true,
    objectFifos: ['fifo_row_a', 'fifo_s_hat', 'fifo_t_row_accum'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 5,
    milestone: 'DR2d',
    name: 'ML-KEM-512 K-PKE KeyGen Terminal Pipeline',
    category: 'FIPS 203',
    algorithm: 'K-PKE KeyGen',
    description: 'Complete on-device K-PKE KeyGen execution with zero host fallback, producing serialized (pk, sk) containers.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 1120,
    textMemoryBytes: 13312,
    tileRamBytes: 53248,
    dmaChannels: 2,
    tilesUsed: 3,
    zeroHostFallback: true,
    objectFifos: ['fifo_seed_d', 'fifo_pk_egress', 'fifo_sk_egress'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 6,
    milestone: 'DR3',
    name: 'ML-KEM-512 K-PKE Encrypt Engine',
    category: 'FIPS 203',
    algorithm: 'K-PKE Encrypt',
    description: 'Dual DMA channel streaming vector encryptor with hardware polynomial compression and ciphertext packing.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 1080,
    textMemoryBytes: 14336,
    tileRamBytes: 57344,
    dmaChannels: 2,
    tilesUsed: 3,
    zeroHostFallback: true,
    objectFifos: ['fifo_pk_in', 'fifo_msg_in', 'fifo_ct_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 7,
    milestone: 'DR4',
    name: 'ML-KEM-512 K-PKE Decrypt Engine',
    category: 'FIPS 203',
    algorithm: 'K-PKE Decrypt',
    description: 'Polynomial inner product INTT transform and 1-bit message decompression with constant-time barrier.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 890,
    textMemoryBytes: 11776,
    tileRamBytes: 47104,
    dmaChannels: 2,
    tilesUsed: 2,
    zeroHostFallback: true,
    objectFifos: ['fifo_ct_in', 'fifo_sk_in', 'fifo_msg_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 8,
    milestone: 'DR5',
    name: 'ML-KEM-512 Full CCA2 KeyGen',
    category: 'FIPS 203',
    algorithm: 'ML-KEM-512 KeyGen',
    description: 'Full CCA2-secure KeyGen containing dual-seed conditioning (d, z) and SHA3-512 domain separation.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 1250,
    textMemoryBytes: 14848,
    tileRamBytes: 59392,
    dmaChannels: 2,
    tilesUsed: 3,
    zeroHostFallback: true,
    objectFifos: ['fifo_entropy_d_z', 'fifo_cca_pk', 'fifo_cca_sk'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 9,
    milestone: 'DR6',
    name: 'ML-KEM-512 Full CCA2 Encaps',
    category: 'FIPS 203',
    algorithm: 'ML-KEM-512 Encaps',
    description: 'On-chip encapsulation engine generating ciphertexts and deriving CCA-shared secret keys in constant time.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 1180,
    textMemoryBytes: 15360,
    tileRamBytes: 61440,
    dmaChannels: 2,
    tilesUsed: 3,
    zeroHostFallback: true,
    objectFifos: ['fifo_pk_in', 'fifo_seed_m', 'fifo_ct_ss_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 10,
    milestone: 'DR7',
    name: 'ML-KEM-512 Full CCA2 Decaps',
    category: 'FIPS 203',
    algorithm: 'ML-KEM-512 Decaps',
    description: 'Complete Fujisaki-Okamoto CCA transform with on-device re-encryption and constant-time implicit rejection.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 1420,
    textMemoryBytes: 15872,
    tileRamBytes: 63488,
    dmaChannels: 2,
    tilesUsed: 4,
    zeroHostFallback: true,
    objectFifos: ['fifo_sk_in', 'fifo_ct_in', 'fifo_ss_egress'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 11,
    milestone: 'DR8',
    name: 'ML-KEM-768/1024 Unified Multi-Tile Pipeline',
    category: 'FIPS 203',
    algorithm: 'ML-KEM-768 & ML-KEM-1024',
    description: 'Scaled multi-tile coordination for Security Categories 3 and 5 with dynamic k=3, k=4 systolic array mapping.',
    testCount: 50,
    passedCount: 50,
    avgRuntimeMs: 2350,
    textMemoryBytes: 15872,
    tileRamBytes: 63488,
    dmaChannels: 2,
    tilesUsed: 4,
    zeroHostFallback: true,
    objectFifos: ['fifo_k3_k4_sync', 'fifo_multi_tile_accum'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 12,
    milestone: 'DR9',
    name: 'NIST FIPS 202 SHA-3 / SHAKE Acceleration',
    category: 'FIPS 202',
    algorithm: 'SHA3-224..512 / SHAKE128..256',
    description: 'Hardware Keccak-f[1600] 64-bit SIMD lane permutation core with arbitrary-length streaming absorb and squeeze.',
    testCount: 122,
    passedCount: 122,
    avgRuntimeMs: 1840,
    textMemoryBytes: 10240,
    tileRamBytes: 40960,
    dmaChannels: 2,
    tilesUsed: 2,
    zeroHostFallback: true,
    objectFifos: ['fifo_sponge_in', 'fifo_sponge_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 13,
    milestone: 'DR10',
    name: 'Sealed Lifecycle & Hardware Zeroization',
    category: 'Hardware/DR0-10',
    algorithm: 'QKD Ingress & Memory Scrubber',
    description: 'Hardware zeroization controller, raw ingress entropy conditioning, and anti-tamper CRC32 validation.',
    testCount: 68,
    passedCount: 68,
    avgRuntimeMs: 1150,
    textMemoryBytes: 6144,
    tileRamBytes: 24576,
    dmaChannels: 2,
    tilesUsed: 1,
    zeroHostFallback: true,
    objectFifos: ['fifo_qkd_ingress', 'fifo_zeroize_control'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 14,
    milestone: 'DR11',
    name: 'ML-DSA-44 KeyGen Pipeline',
    category: 'FIPS 204',
    algorithm: 'ML-DSA-44 KeyGen',
    description: '4x4 lattice matrix expansion, secret noise vector generation (eta=2), and public key Power2Round compression.',
    testCount: 25,
    passedCount: 25,
    avgRuntimeMs: 1490,
    textMemoryBytes: 14848,
    tileRamBytes: 59392,
    dmaChannels: 2,
    tilesUsed: 3,
    zeroHostFallback: true,
    objectFifos: ['fifo_xi_seed', 'fifo_pk_t1_out', 'fifo_sk_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 15,
    milestone: 'DR12',
    name: 'ML-DSA-44 Signature Engine',
    category: 'FIPS 204',
    algorithm: 'ML-DSA-44 Sign',
    description: 'On-device rejection sampling loop, HighBits/LowBits decomposition, and hint bit vector generation.',
    testCount: 30,
    passedCount: 30,
    avgRuntimeMs: 1820,
    textMemoryBytes: 15360,
    tileRamBytes: 61440,
    dmaChannels: 2,
    tilesUsed: 4,
    zeroHostFallback: true,
    objectFifos: ['fifo_sk_msg_in', 'fifo_sig_hint_out'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 16,
    milestone: 'DR13',
    name: 'ML-DSA-44 Signature Verifier',
    category: 'FIPS 204',
    algorithm: 'ML-DSA-44 Verify',
    description: 'Matrix reconstruction from public key rho seed, UseHint verification, and infinity norm bound check.',
    testCount: 30,
    passedCount: 30,
    avgRuntimeMs: 1360,
    textMemoryBytes: 13824,
    tileRamBytes: 55296,
    dmaChannels: 2,
    tilesUsed: 3,
    zeroHostFallback: true,
    objectFifos: ['fifo_pk_sig_in', 'fifo_verify_result'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 17,
    milestone: 'DR14',
    name: 'ML-DSA-65 Unified Lifecycle',
    category: 'FIPS 204',
    algorithm: 'ML-DSA-65 KeyGen/Sign/Verify',
    description: '6x5 lattice dimension scaling for Security Category 3 with eta=4 secret distributions on AIE2 cores.',
    testCount: 85,
    passedCount: 85,
    avgRuntimeMs: 2780,
    textMemoryBytes: 15872,
    tileRamBytes: 63488,
    dmaChannels: 2,
    tilesUsed: 4,
    zeroHostFallback: true,
    objectFifos: ['fifo_mldsa65_pipeline'],
    status: 'CERTIFIED',
  },
  {
    gateNumber: 18,
    milestone: 'DR15',
    name: 'ML-DSA-87 High-Security Core',
    category: 'FIPS 204',
    algorithm: 'ML-DSA-87 KeyGen/Sign/Verify',
    description: 'Maximum Security Category 5 (8x7 lattice matrix) executed entirely within AIE2 hardware memory bounds.',
    testCount: 85,
    passedCount: 85,
    avgRuntimeMs: 3190,
    textMemoryBytes: 15872,
    tileRamBytes: 63488,
    dmaChannels: 2,
    tilesUsed: 4,
    zeroHostFallback: true,
    objectFifos: ['fifo_mldsa87_pipeline'],
    status: 'CERTIFIED',
  },
];

export const TOTAL_SILICON_TESTS = SILICON_GATES.reduce((sum, g) => sum + g.testCount, 0); // 736
export const TOTAL_SILICON_PASSED = SILICON_GATES.reduce((sum, g) => sum + g.passedCount, 0); // 736
